# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
load_path:  ''
print_freq:  10
save_freq:  1
val_freq:  10000
log_dir:  'logs'
rng_seed:  0

# ---------------------------------------------------------------------------- #
# Training options
# ---------------------------------------------------------------------------- #
start_epoch:  1
epochs: 2000
train_steps: 300
learning_rate:  0.01
optimizer:  'adam'
lr_scheduler:  'step'  # step,cosine
warmup_epoch:  -1
warmup_multiplier:  100
lr_decay_steps:  [10,15]
lr_decay_rate: 0.5
weight_decay:  0.001
momentum:  0.9
grad_clip_norm: 100.0

# ---------------------------------------------------------------------------- #
# Data options
# ---------------------------------------------------------------------------- #

data_name: 'sceneflow'
task: 'stereo_depth'
data_root: ''
batch_size:  1
num_workers:  7
max_disp: 192
#height: 256  # 训练时输入图像高
#width: 512  # 训练时输入图像宽
height: 240  # 训练时输入图像高
width: 576  # 训练时输入图像宽

# data augmentation
augment_scale_size: 0
augment_input_size: 0
augment_brightness: 0.4
augment_contrast: 0.4
augment_saturation: 0.4
augment_lighting: 0.1

# ---------------------------------------------------------------------------- #
# Model
# ---------------------------------------------------------------------------- #
use_batch_norm: True
batch_norm_momentum: 0.1
model_name: 'ga_net'

