# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
load_path:  ''
print_freq:  10
save_freq:  1
val_freq:  2000
log_dir:  'logs'
rng_seed:  54321

# ---------------------------------------------------------------------------- #
# Training options
# ---------------------------------------------------------------------------- #
start_epoch:  1
epochs: 30000
train_steps: 300
learning_rate:  0.001
optimizer:  'adam'
lr_scheduler:  'step'  # step,cosine
warmup_epoch:  3
warmup_multiplier:  100
lr_decay_steps:  [8, 15]
lr_decay_rate:  0.1
weight_decay:  0.0
momentum:  0.9
grad_clip_norm: 100.0

# ---------------------------------------------------------------------------- #
# Data options
# ---------------------------------------------------------------------------- #

data_name: 'sceneflow'
task: 'stereo_depth'
data_root: ''
batch_size:  2
num_workers:  7
max_disp: 192
height: 256  # 训练时输入图像高
width: 512  # 训练时输入图像宽

# ---------------------------------------------------------------------------- #
# Model
# ---------------------------------------------------------------------------- #

model_name: 'pasm'

