# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
load_path:  ''
print_freq:  12
save_freq:  1
val_freq:  20000
log_dir:  'logs'
rng_seed:  0

# ---------------------------------------------------------------------------- #
# Training options
# ---------------------------------------------------------------------------- #
start_epoch:  1
epochs: 2000
train_steps: 300
learning_rate:  0.0001
optimizer:  'adam'
lr_scheduler:  'step'  # step,cosine
warmup_epoch:  10
warmup_multiplier:  100
lr_decay_steps:  [70, 120]
lr_decay_rate:  0.1
weight_decay:  0.0
momentum:  0.9
grad_clip_norm: 100.0

# ---------------------------------------------------------------------------- #
# Data options
# ---------------------------------------------------------------------------- #

data_name: 'kitti_2015'
task: 'stereo_depth'
data_root: ''
batch_size:  2
num_workers:  7
max_disp: 192
height: 256  # 训练时输入图像高
width: 512  # 训练时输入图像宽

# ---------------------------------------------------------------------------- #
# Model
# ---------------------------------------------------------------------------- #
model_name: 'pasm'

